apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp8-devops
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: tp8-web
  template:
    metadata:
      labels:
        app: tp8-web
    spec:
      volumes:
        - name: vol-img
          persistentVolumeClaim:
            claimName: img-pvc-1
      containers:
        - name: tp8-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
