apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: img-vol-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: img-vol
