apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: img-pvc-1
spec:
  accessModes:
    - {{ .Values.pvc.accessModes }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
  selector:
    matchLabels:
      {{- toYaml .Values.pvc.selectorMatchLabels | nindent 6 }}

