apiVersion: v1
kind: Service
metadata:
  name: tp8-devops
spec:
  selector:
    app: tp8-web
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
