apiVersion: v1
kind: PersistentVolume
metadata:
  name: img-vol
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/imagenes"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: img-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: img-vol