apiVersion: v1
kind: PersistentVolume
metadata:
  name: img-vol-1
spec:
  capacity:
    storage: {{ .Values.volume.capacity }}
  accessModes:
    - {{ .Values.volume.accessModes }}
  hostPath:
    path: "{{ .Values.volume.hostPath }}"

