apiVersion: v2
name: tp9-devops
description: Intento de tp9

type: application

<<<<<<< HEAD
version: 0.1.3  # Versión del chart. Sigue las convenciones de versionado semántico.
=======
version: 0.1.1  # Versión del chart
>>>>>>> 3730e2e (Segundo intento)

appVersion: "1.0"  # Versión de la aplicación
