deployment:
  replicas: 3
  revisionHistoryLimit: 3

service:
  port: 80
  targetPort: 80
  type: NodePort

pvc:
  accessModes: ReadWriteOnce
  size: 1Gi
  selectorMatchLabels:
    type: img-vol

volume:
  capacity: 1Gi
  accessModes: ReadWriteOnce
  hostPath: "/home/imagenes"

image:
  repository: francogcuenca/tp8-web
  tag: "1.5"
